name: Build Workflow

on: [push]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Notify slack success
        if: success()
        id: slack # IMPORTANT: reference this step ID value in future Slack steps
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: app-alerts
          status: STARTING
          color: warning

      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Decode All configuration files
      - name: Decode all configuration files
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
          FACEBOOK_KEYS: ${{ secrets.FACEBOOK_KEYS }}
          LASTFM_KEYS: ${{ secrets.LASTFM_KEYS }}
          SSL_CERTFICATION: ${{ secrets.SSL_CERTFICATION }}
        run: |
          echo FIREBASE_CONFIG > app/google-services.json
          echo LOCAL_PROPERTIES > ./local.properties
          echo FACEBOOK_KEYS > app/src/main/res/values/facebook_key.xml
          echo LASTFM_KEYS > feature/explore/src/main/res/values/keys.xml
          echo SSL_CERTFICATION > core/src/main/res/raw/mycertfile.crt

      # Step 4: Yun your unit tests
      #      - name: Run Unit Tests
      #        run: ./gradlew testStagingDebugUnitTest

      # Step 4: Assemble debug apk to send to firebase test lab
      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

      # Send the notification to slack
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: app-alerts
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: app-alerts
          status: FAILED
          color: danger
